# This workflow will do a clean install of node dependencies, build the source code, perform lint checks and run tests across different versions of node.
# This workflow will only be run for pull requests to either master or develop branch provided there are no merge conflicts. 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# NB: check if types: [opened, reopened] is necessary.  
name: Lint & Build

on:
  pull_request:
    branches: [ "master", "develop"]
    types: [opened, reopened]

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout âœ”ï¸
        uses: actions/checkout@v4

      - name: Setup bun ğŸ¥Ÿ
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies ğŸ“
        run: bun install

      - name: Run Lint ğŸ§¼
        run: bun run lint

      - name: Build ğŸ› ï¸
        run: bun run build
